# Generated by Django 4.0.5 on 2022-06-20 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_game_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=100)),
                ('correct', models.BooleanField(default=False)),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.game')),
            ],
        ),
    ]
