# Generated by Django 4.0.5 on 2022-06-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='closest',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guess',
            name='guess',
            field=models.CharField(default='', max_length=100),
        ),
    ]
